### ISSUE TITLE
[Bug] Cannot find `fs.promises`

### ISSUE THREAD

**Issue by johannesschobel** [vegardit/prisma-generator-nestjs-dto#108]
Dear team,

thanks a lot for this package. It seems very promising, and I would like to evaluate it for further usage. Unfortunately, I was not able to get it to run properly.

My Schema file looks like this (only important parts)

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl"]
}

generator nestjsDto {
  provider                        = "prisma-generator-nestjs-dto"
  output                          = "../src/generated/nestjs-dto"
  outputToNestJsResourceStructure = "false"
  exportRelationModifierClasses   = "true"
  reExport                        = "false"
  createDtoPrefix                 = "Create"
  updateDtoPrefix                 = "Update"
  dtoSuffix                       = "Dto"
  entityPrefix                    = ""
  entitySuffix                    = ""
  fileNamingStyle                 = "camel"
}

datasource db {
  provider = "postgresql"
  url      = env("DB_CONNECTION_STRING")
}
```

the error i get is like this:

```bash
> npx prisma generate

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Generator at prisma-generator-nestjs-dto could not start:

internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'node:fs/promises'
Require stack:
- /home/x/projects/y/node_modules/@vegardit/prisma-generator-nestjs-dto/dist/index.js
- /home/x/projects/y/node_modules/@vegardit/prisma-generator-nestjs-dto/dist/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/x/projects/y/node_modules/@vegardit/prisma-generator-nestjs-dto/dist/index.js:7:36)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/x/projects/y/node_modules/@vegardit/prisma-generator-nestjs-dto/dist/index.js',
    '/home/x/projects/y/node_modules/@vegardit/prisma-generator-nestjs-dto/dist/cli.js'
  ]
}
```

Am i missing something?
All the best,
Johannes

**Comment by benkroeger** [comment]
please use a current node version. Seems like the engine restrictions in our package.json are not sufficient.

https://nodejs.org/api/modules.html#core-modules

![image](https://user-images.githubusercontent.com/7782055/162478408-fbc5f8e6-4b99-4166-b1fe-7dc14df7c839.png)
