### ISSUE TITLE
Self relation Problem

### ISSUE THREAD

**Issue by Manugr21** [vegardit/prisma-generator-nestjs-dto#89]
I have a simple schema:
```
generator nestjsDto {
  provider                        = "prisma-generator-nestjs-dto"
  exportRelationModifierClasses   = "true"
  reExport                        = "true"
  createDtoPrefix                 = "Create"
  updateDtoPrefix                 = "Update"
  dtoSuffix                       = "Dto"
  entityPrefix                    = ""
  entitySuffix                    = ""
  fileNamingStyle                 = "kebab"
  output                          = "../src"
  outputToNestJsResourceStructure = "true"
}

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Puesto {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  nombre String
  /// @DtoCreateOptional
  /// @DtoUpdateOptional
  /// @DtoRelationCanConnectOnCreate
  /// @DtoRelationCanConnectOnUpdate
  jefeInmediato   Puesto?  @relation("JefeEmpleados", fields: [jefeInmediatoId], references: [id])
  jefeInmediatoId Int?
  personalAcargo  Puesto[] @relation("JefeEmpleados")
  @@map("puestos")
}
```

But when I compile then I keep getting this error on the connect DTO:
```
 Cannot find module 'C:/sistema-gestion-riesgo/src/puesto/dto/connect-puesto.dto'
Require stack:
- C:\sistema-gestion-riesgo\dist\puesto\dto\create-puesto.dto.js
- C:\sistema-gestion-riesgo\dist\puesto\puesto.controller.js
- C:\sistema-gestion-riesgo\dist\puesto\puesto.module.js
- C:\sistema-gestion-riesgo\dist\app.module.js
- C:\sistema-gestion-riesgo\dist\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.type (C:\sistema-gestion-riesgo\dist\puesto\dto\create-puesto.dto.js:15:57)
    at SchemaObjectFactory.mergePropertyWithMetadata (C:\sistema-gestion-riesgo\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:116:38)
    at C:\sistema-gestion-riesgo\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:79:35
    at Array.map (<anonymous>)
    at SchemaObjectFactory.extractPropertiesFromType (C:\sistema-gestion-riesgo\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:78:52)
    at SchemaObjectFactory.exploreModelSchema (C:\sistema-gestion-riesgo\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:92:41) 
```

As additional information my tsconfig.JSON file

```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": false,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
```

**Comment by benkroeger** [comment]
please provide a minimal reproduction repo.
also share a list of the files in `C:/sistema-gestion-riesgo/src/puesto/dto/`

**Comment by Manugr21** [comment]
I found the problem. For my dto's to work I needed to add an ApiProperty annotation for typescript or nest to work properly.
I don't fully understand what's happening but adding them made my code functional.

```
import {
  ApiExtraModels,
  ApiProperty,
} from '@nestjs/swagger';
import { ConnectPuestoDto } from './connect-puesto.dto';

export class CreatePuestoJefeInmediatoRelationInputDto {
  **@ApiProperty({
    type: () => ConnectPuestoDto,
  })**
  connect: ConnectPuestoDto;
}

@ApiExtraModels(
  ConnectPuestoDto,
  CreatePuestoJefeInmediatoRelationInputDto,
)
export class CreatePuestoDto {
  nombre: string;
  **@ApiProperty({
    type: () =>
      CreatePuestoJefeInmediatoRelationInputDto,
  })**
  jefeInmediato?: CreatePuestoJefeInmediatoRelationInputDto;
}
```
**Question!**
Why does the dto generator adds the ApiExtraModels annotation but doesn't add the ApiProperty for model types?

**Comment by benkroeger** [comment]
please check if you have all set annotations in your schema correctly...

https://github.com/Manugr21/SGR/blob/9cb620b63ac0cffe414c6f24eca82ab216853d27/prisma/schema.prisma#L46

**Comment by benkroeger** [comment]
Closing this issue as there was no feedback for 21 days
